parameters:
  container: !php/const CONTAINER
  root.path: !php/const ROOT

services:
  db:
    class: DB
    arguments: ['%env(DB_HOST)%', '%env(DB_NAME)%', '%env(DB_USER)%', '%env(DB_PASS)%']
  resolver:
    class: News\Core\Routing\HandlerResolver
    arguments: ['%container%']
  twig_filesystem:
    class: Twig_Loader_Filesystem
    arguments: ['%root.path%/resources/templates']