parameters:
  twig.options:
    debug: '%env(TWIG_DEBUG)%'
    cache: '%root.path%/cache/templates'

services:
  app.http.controller:
    class: 'News\Core\Http\Controller'
    abstract: true
    calls:
      - method: setRequest
        arguments: ['@symfony.request']
      - method: setTwig
        arguments: ['@twig']

  app.routing.dispatcher:
    public: true
    class: 'News\Core\Routing\Dispatcher'
    arguments: ['@app.routing.routing', '@service_container']

  app.routing.routing:
    class: 'News\Core\Routing\Routing'
    factory: 'News\Core\Routing\Routing::getMatcherAttributes'
    arguments:
      $locator: '@symfony.file.locator'
      $request: '@symfony.request'

  app.db.repository:
    class: News\Core\Repository\Repository
    abstract: true
    calls:
      - method: setDbInstance
        arguments:
          $db: '@db'

  db:
    class: DB
    arguments: ['%env(DB_HOST)%', '%env(DB_NAME)%', '%env(DB_USER)%', '%env(DB_PASS)%']
    public: true
  twig.filesystem:
    class: Twig_Loader_Filesystem
    arguments: ['%root.path%/resources/templates']
  twig:
    class: Twig_Environment
    arguments: ['@twig.filesystem', '%twig.options%']
    public: true
  symfony.request:
    class: Symfony\Component\HttpFoundation\Request
    factory: 'Symfony\Component\HttpFoundation\Request::createFromGlobals'

  News\Http\Controllers\:
    public: true
    parent: app.http.controller
    resource: '../src/Http/Controllers/*'
    autowire: true
    autoconfigure: false

  News\Repositories\:
    public: true
    parent: app.db.repository
    resource: "../src/Repositories/*"
    autowire: true
    autoconfigure: false
  