parameters:
  twig.options:
    debug: '%env(TWIG_DEBUG)%'
    cache: '%root.path%/cache/templates'

services:
  app.routing.dispatcher:
    public: true
    class: 'News\Core\Routing\Dispatcher'
    arguments: ['@app.routing.routing', '@service_container']

  app.routing.routing:
    class: 'News\Core\Routing\Routing'
    factory: 'News\Core\Routing\Routing::getMatcherAttributes'
    arguments:
      $locator: '@symfony.file.locator'
      $request: '@symfony.request'
  db:
    class: DB
    arguments: ['%env(DB_HOST)%', '%env(DB_NAME)%', '%env(DB_USER)%', '%env(DB_PASS)%']
    public: true
  twig.filesystem:
    class: Twig_Loader_Filesystem
    arguments: ['%root.path%/resources/templates']
  twig:
    class: Twig_Environment
    arguments: ['@twig.filesystem', '%twig.options%']
    public: true
  symfony.request:
    class: Symfony\Component\HttpFoundation\Request
    factory: 'Symfony\Component\HttpFoundation\Request::createFromGlobals'